version: "3.9"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27027:27017
    volumes:
      - mongodb_data_container:/data/db
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/nginx
    ports:
      - "3050:80"
  api:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/server
    volumes:
      - /app/node_modules
      - ./packages/server:/app
    environment:
      - HOST_MONGO=${HOST_MONGO}
      - APP_HOST=${APP_HOST}
      - APP_PORT=${APP_PORT}
      - APP_ENV=${APP_ENV}
      - APP_BASE_ROUTE=${APP_BASE_ROUTE}
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./packages/client
    volumes:
      - /app/node_modules
      - ./packages/client:/app
    environment:
      - REACT_APP_QUERY_API=${APP_BASE_ROUTE}
volumes:
  mongodb_data_container:
